from sqlalchemy import Column, Integer, Float, String, DateTime, Boolean, ForeignKey
from sqlalchemy.orm import relationship, declarative_base
from datetime import datetime

Base = declarative_base()


class Cycle(Base):
    """Cycle type definition.

    Uses British English terminology.
    """
    __tablename__ = "cycles"
    id = Column(Integer, primary_key=True)
    user_id = Column(String, nullable=False)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    start = Column(DateTime)
    end = Column(DateTime)
    timezone_offset = Column(String)
    score_state = Column(String)
    strain = Column(Float)
    kilojoule = Column(Float)
    average_heart_rate = Column(Float)
    max_heart_rate = Column(Float)

    # relationships
    recoveries = relationship("Recovery", back_populates="cycle", cascade="all, delete-orphan")
    workouts = relationship("Workout", back_populates="cycle", cascade="all, delete-orphan")


from sqlalchemy import Column, Integer, String, DateTime, Float, Boolean
from sqlalchemy.orm import relationship


class Sleep(Base):
    """Sleep type definition.

    Uses British English terminology.
    """
    __tablename__ = "sleep"

    id = Column(Integer, primary_key=True, autoincrement=True)
    whoop_id = Column(String, unique=True, nullable=False)  # WHOOP API string ID
    user_id = Column(String, nullable=False)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    start = Column(DateTime)
    end = Column(DateTime)
    timezone_offset = Column(String)
    nap = Column(Boolean)
    score_state = Column(String)

    respiratory_rate = Column(Float)
    sleep_performance_percentage = Column(Float)
    sleep_consistency_percentage = Column(Float)
    sleep_efficiency_percentage = Column(Float)

    # --- Stage summary fields ---
    total_time_in_bed_time_milli = Column(Integer)
    total_awake_time_milli = Column(Integer)
    total_no_data_time_milli = Column(Integer)
    total_slow_wave_sleep_time_milli = Column(Integer)
    total_rem_sleep_time_milli = Column(Integer)
    sleep_cycle_count = Column(Integer)
    disturbance_count = Column(Integer)

    # --- Sleep needed fields ---
    baseline_sleep_needed_milli = Column(Integer)
    need_from_sleep_debt_milli = Column(Integer)
    need_from_recent_strain_milli = Column(Integer)
    need_from_recent_nap_milli = Column(Integer)

    # Relationships
    recoveries = relationship("Recovery", back_populates="sleep", cascade="all, delete-orphan")


class Recovery(Base):
    """Recovery type definition.

    Uses British English terminology.
    """
    __tablename__ = "recovery"
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String, nullable=False)
    cycle_id = Column(Integer, ForeignKey("cycles.id"))
    sleep_id = Column(Integer, ForeignKey("sleep.id"))
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    score_state = Column(String)
    user_calibrating = Column(Boolean)
    recovery_score = Column(Float)
    resting_heart_rate = Column(Float)
    hrv_rmssd_milli = Column(Float)
    spo2_percentage = Column(Float)
    skin_temp_celsius = Column(Float)
    # relationships
    cycle = relationship("Cycle", back_populates="recoveries")
    sleep = relationship("Sleep", back_populates="recoveries")

    def recovery_category(self):
        """Recovery category.

        Returns:
            Result generated by this routine.

        Example:
            # Example usage
            result = recovery_category()
            _ = result

        Uses British English terminology.
        """
        if self.recovery_score >= 67:
            return "Green"
        elif 34 <= self.recovery_score < 67:
            return "Yellow"
        else:
            return "Red"

    def is_weekend(self) -> bool:
        """Is weekend.

        Returns:
            Result generated by this routine.

        Example:
            # Example usage
            result = is_weekend()
            _ = result

        Uses British English terminology.
        """
        if self.created_at:
            return self.created_at.weekday() > 4  # 5 = Saturday, 6 = Sunday
        return False


class Workout(Base):
    """Workout type definition.

    Uses British English terminology.
    """
    __tablename__ = "workout"

    id = Column(Integer, primary_key=True, autoincrement=True)
    whoop_id = Column(String, unique=True, nullable=False)  # WHOOP API string ID
    user_id = Column(String, nullable=False)
    cycle_id = Column(Integer, ForeignKey("cycles.id"))
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    start = Column(DateTime)
    end = Column(DateTime)
    timezone_offset = Column(String)
    sport_id = Column(Integer)
    score_state = Column(String)
    strain = Column(Float)
    average_heart_rate = Column(Float)
    max_heart_rate = Column(Float)
    kilojoule = Column(Float)
    percent_recorded = Column(Float)
    distance_meter = Column(Float)
    altitude_gain_meter = Column(Float)
    altitude_change_meter = Column(Float)

    # New zone duration fields (in minutes)
    zone_zero_minutes = Column(Float)
    zone_one_minutes = Column(Float)
    zone_two_minutes = Column(Float)
    zone_three_minutes = Column(Float)
    zone_four_minutes = Column(Float)
    zone_five_minutes = Column(Float)

    cycle = relationship("Cycle", back_populates="workouts")


class WithingsWeight(Base):
    """WithingsWeight type definition.

    Uses British English terminology.
    """
    __tablename__ = "withings_weight"

    id = Column(Integer, primary_key=True)
    user_id = Column(String, nullable=False)
    grpid = Column(Integer)  # Withings group ID
    deviceid = Column(String)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    date = Column(Integer)  # Unix timestamp from Withings
    datetime = Column(DateTime)  # Converted datetime
    timezone = Column(String)
    comment = Column(String)
    category = Column(Integer)  # 1 for real measures, 2 for objectives

    # Weight measurements
    weight_kg = Column(Float)
    height_m = Column(Float)
    fat_free_mass_kg = Column(Float)
    fat_ratio_percent = Column(Float)
    fat_mass_kg = Column(Float)

    # Additional body composition (optional)
    muscle_mass_kg = Column(Float)
    bone_mass_kg = Column(Float)
    hydration_kg = Column(Float)
    visceral_fat = Column(Float)

    def __repr__(self):
        return f"<WithingsWeight(user_id='{self.user_id}', weight={self.weight_kg}kg, date='{self.datetime}')>"

    def bmi(self):
        """Calculate BMI if both weight and height are available"""
        if self.weight_kg and self.height_m and self.height_m > 0:
            return round(self.weight_kg / (self.height_m**2), 1)
        return None

    def weight_category(self):
        """BMI-based weight category"""
        bmi = self.bmi()
        if bmi is None:
            return "Unknown"
        elif bmi < 18.5:
            return "Underweight"
        elif 18.5 <= bmi < 25:
            return "Normal"
        elif 25 <= bmi < 30:
            return "Overweight"
        else:
            return "Obese"


class WithingsHeartRate(Base):
    """WithingsHeartRate type definition.

    Uses British English terminology.
    """
    __tablename__ = "withings_heart_rate"

    id = Column(Integer, primary_key=True)
    user_id = Column(String, nullable=False)
    grpid = Column(Integer)  # Withings group ID
    deviceid = Column(String)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    date = Column(Integer)  # Unix timestamp
    datetime = Column(DateTime)  # Converted datetime
    timezone = Column(String)
    category = Column(Integer)

    # Heart rate and blood pressure measurements
    heart_rate_bpm = Column(Float)
    systolic_bp_mmhg = Column(Float)
    diastolic_bp_mmhg = Column(Float)

    def __repr__(self):
        return f"<WithingsHeartRate(user_id='{self.user_id}', hr={self.heart_rate_bpm}bpm, date='{self.datetime}')>"

    def bp_category(self):
        """Blood pressure category based on AHA guidelines"""
        if not self.systolic_bp_mmhg or not self.diastolic_bp_mmhg:
            return "Unknown"

        systolic = self.systolic_bp_mmhg
        diastolic = self.diastolic_bp_mmhg

        if systolic < 120 and diastolic < 80:
            return "Normal"
        elif systolic < 130 and diastolic < 80:
            return "Elevated"
        elif (130 <= systolic < 140) or (80 <= diastolic < 90):
            return "Stage 1 High"
        elif (140 <= systolic < 180) or (90 <= diastolic < 120):
            return "Stage 2 High"
        else:
            return "Crisis"


class Recommendation(Base):
    """Daily recommendations generated by the daily engine."""
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    date = Column(DateTime, nullable=False)  # Date the recommendation was for
    action_text = Column(String, nullable=False)
    category = Column(String, nullable=False)  # training, sleep, recovery, lifestyle
    target_metric = Column(String)  # e.g. "sleep_hours", "recovery_score"
    target_value = Column(Float)  # e.g. 8.0 for sleep hours
    created_at = Column(DateTime, default=datetime.utcnow)

    outcomes = relationship(
        "RecommendationOutcome", back_populates="recommendation", cascade="all, delete-orphan"
    )


class RecommendationOutcome(Base):
    """Tracks whether recommendations were followed and their outcomes."""
    __tablename__ = "recommendation_outcomes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    recommendation_id = Column(Integer, ForeignKey("recommendations.id"), nullable=False)
    actual_metric = Column(String)  # Same as target_metric
    actual_value = Column(Float)  # What actually happened
    followed = Column(Boolean)  # Was the recommendation followed?
    outcome_delta = Column(Float)  # Difference from target
    recovery_score = Column(Float)  # Recovery score on the outcome day
    recorded_at = Column(DateTime, default=datetime.utcnow)

    recommendation = relationship("Recommendation", back_populates="outcomes")


class ProactiveMessageLog(Base):
    """Tracks proactive nudges so the planner can apply cooldowns and escalation."""
    __tablename__ = "proactive_message_log"

    id = Column(Integer, primary_key=True, autoincrement=True)
    chat_id = Column(Integer, nullable=False)
    mode = Column(String, nullable=False)
    intent = Column(String, nullable=False)
    trigger_fingerprint = Column(String)
    reason = Column(String)
    evidence_json = Column(String)
    prompt = Column(String, nullable=False)
    telegram_message_id = Column(Integer)
    sent_at = Column(DateTime, default=datetime.utcnow, nullable=False)


# ---------------------------------------------------------------------------
# Biomarker analyser (Phase 0 prototype) — see docs/features/BIOMARKER_*.md
# Governed by the intended-purpose statement: display + generic education only,
# single result set, NO interpretation. The agent must NEVER surface lab_status.
# ---------------------------------------------------------------------------


class BiomarkerReport(Base):
    """A single blood-test report (one active result set at a time).

    Single-result-set is a structural control: seeding truncates and reloads
    these tables, so the DB can never hold two timepoints — longitudinal
    monitoring is impossible by construction, not just by policy.
    """
    __tablename__ = "biomarker_report"

    report_id = Column(Integer, primary_key=True, autoincrement=True)
    order_number = Column(String)
    taken_on = Column(DateTime)  # Sample collection date
    lab_provider = Column(String)
    report_status = Column(String)
    biological_sex = Column(String)
    source_file = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)

    results = relationship(
        "BiomarkerResult", back_populates="report", cascade="all, delete-orphan"
    )


class BiomarkerResult(Base):
    """One analyte row, shaped after OMOP MEASUREMENT (no vocabulary mapping yet).

    ``lab_status`` holds the lab's own verdict ("High"/"Low"/…). It is stored
    for audit/future rungs but is NEVER selected by the agent-facing CRUD or
    tools — surfacing it would be interpretation. ``measurement_concept_id`` /
    ``unit_concept_id`` are nullable LOINC/UCUM hooks for a later OMOP export.
    """
    __tablename__ = "biomarker_results"

    result_id = Column(Integer, primary_key=True, autoincrement=True)
    report_id = Column(Integer, ForeignKey("biomarker_report.report_id"), nullable=False)
    source_biomarker_name = Column(String, nullable=False)  # verbatim from the report
    category = Column(String)  # neutral body-system grouping
    result_raw = Column(String)  # raw cell text, e.g. "<6.72", "Negative", "144.0"
    value_as_number = Column(Float)  # parsed numeric, nullable
    value_as_concept = Column(String)  # qualitative result, e.g. "Negative"
    operator = Column(String)  # "<", "=", ">"
    unit = Column(String)
    range_low = Column(Float)  # the lab's own range; nullable (often one-sided)
    range_high = Column(Float)
    lab_status = Column(String)  # STORED, NEVER SURFACED
    measurement_concept_id = Column(Integer)  # nullable LOINC hook (unused in Phase 0)
    unit_concept_id = Column(Integer)  # nullable UCUM hook (unused in Phase 0)

    report = relationship("BiomarkerReport", back_populates="results")


class BiomarkerEducation(Base):
    """Generic, biomarker-keyed glossary: definition + normal physiological function.

    Non-personalised and condition-free by construction. Content must never
    describe what abnormal levels indicate or cause (the Step 6 education line).
    """
    __tablename__ = "biomarker_education"

    source_biomarker_name = Column(String, primary_key=True)
    what_it_is = Column(String)
    physiological_function = Column(String)


class SafetyAudit(Base):
    """Per-output log from the graph-internal safety node."""
    __tablename__ = "safety_audit"

    audit_id = Column(Integer, primary_key=True, autoincrement=True)
    surface = Column(String)  # "langgraph" | "telegram" | …
    verdict = Column(String)  # "pass" | "blocked"
    reason = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)
