"""Verified public surface inventory for the AGE-6 migration work.

This module is intentionally data-only. It captures the current public routes and
runtime entrypoints that later migration tickets will use as their execution
baseline.
"""

from __future__ import annotations

from typing import Literal, TypedDict

from whoopdata.api.public_surface_contract import (
    CanonicalSurface,
    EntrypointRole,
    EntrypointSurface,
    RouteKind,
    RouteRole,
    build_legacy_route_guidance,
)

RouteMigrationAction = Literal[
    "keep_page_only",
    "move_to_canonical_namespace",
    "keep_temporary_adapter",
    "deduplicate_then_keep_temporary_adapter",
]
EntrypointKind = Literal["make_target", "project_script", "python_script", "langgraph_graph"]
EntrypointMigrationAction = Literal[
    "consolidate_under_agent_surface",
    "keep_convenience_only",
    "keep_dev_only",
    "keep_primary",
]
TEMPORARY_ADAPTER_MIGRATION_ACTIONS = frozenset(
    {
        "keep_temporary_adapter",
        "deduplicate_then_keep_temporary_adapter",
    }
)


class RouteMigrationEntry(TypedDict):
    methods: tuple[str, ...]
    current_path: str
    handler_names: tuple[str, ...]
    source_refs: tuple[str, ...]
    current_kind: RouteKind
    current_role: RouteRole
    canonical_surface: CanonicalSurface
    target_path: str
    migration_action: RouteMigrationAction
    notes: str


class EntrypointMigrationEntry(TypedDict):
    kind: EntrypointKind
    current_identifier: str
    source_refs: tuple[str, ...]
    current_role: EntrypointRole
    primary_surface: EntrypointSurface
    target: str
    migration_action: EntrypointMigrationAction
    notes: str


def is_temporary_adapter_route(entry: RouteMigrationEntry) -> bool:
    return (
        entry["current_role"] == "legacy_alias"
        and entry["migration_action"] in TEMPORARY_ADAPTER_MIGRATION_ACTIONS
    )


def route(
    current_path: str,
    *,
    handler_names: tuple[str, ...],
    source_refs: tuple[str, ...],
    canonical_surface: CanonicalSurface,
    target_path: str,
    methods: tuple[str, ...] = ("GET",),
    current_kind: RouteKind = "api",
    current_role: RouteRole = "resource",
    migration_action: RouteMigrationAction = "move_to_canonical_namespace",
    notes: str = "",
) -> RouteMigrationEntry:
    if current_role == "legacy_alias" and migration_action in TEMPORARY_ADAPTER_MIGRATION_ACTIONS:
        guidance = build_legacy_route_guidance(target_path)
        if guidance not in notes:
            notes = f"{notes} {guidance}".strip() if notes else guidance
    return {
        "methods": methods,
        "current_path": current_path,
        "handler_names": handler_names,
        "source_refs": source_refs,
        "current_kind": current_kind,
        "current_role": current_role,
        "canonical_surface": canonical_surface,
        "target_path": target_path,
        "migration_action": migration_action,
        "notes": notes,
    }


def entrypoint(
    current_identifier: str,
    *,
    kind: EntrypointKind,
    source_refs: tuple[str, ...],
    current_role: EntrypointRole,
    primary_surface: EntrypointSurface,
    target: str,
    migration_action: EntrypointMigrationAction,
    notes: str = "",
) -> EntrypointMigrationEntry:
    return {
        "kind": kind,
        "current_identifier": current_identifier,
        "source_refs": source_refs,
        "current_role": current_role,
        "primary_surface": primary_surface,
        "target": target,
        "migration_action": migration_action,
        "notes": notes,
    }


FRAMEWORK_MANAGED_ROUTE_PREFIXES = ("/docs", "/redoc", "/openapi", "/static")


WEB_ROUTE_MIGRATION_MATRIX: tuple[RouteMigrationEntry, ...] = (
    route(
        "/",
        handler_names=("homepage",),
        source_refs=("whoopdata/api/web_routes.py:9-12",),
        canonical_surface="web",
        target_path="/",
        current_kind="page",
        current_role="web_page",
        migration_action="keep_page_only",
        notes="Landing page remains a web-only surface.",
    ),
    route(
        "/analytics",
        handler_names=("analytics_page",),
        source_refs=("whoopdata/api/web_routes.py:15-18",),
        canonical_surface="web",
        target_path="/analytics",
        current_kind="page",
        current_role="web_page",
        migration_action="keep_page_only",
        notes="Keep the page route and move JSON analytics endpoints off the top-level /analytics namespace.",
    ),
    route(
        "/report",
        handler_names=("weekly_report_page",),
        source_refs=("whoopdata/api/web_routes.py:21-24",),
        canonical_surface="web",
        target_path="/report",
        current_kind="page",
        current_role="web_page",
        migration_action="keep_page_only",
        notes="Weekly report page remains a web-only route.",
    ),
    route(
        "/dashboard/",
        handler_names=("dashboard_home",),
        source_refs=("whoopdata/api/dashboard_page_routes.py:9-12",),
        canonical_surface="web",
        target_path="/dashboard",
        current_kind="page",
        current_role="web_page",
        migration_action="keep_page_only",
        notes="Current page route includes a trailing slash; target contract keeps dashboard as a page-only surface.",
    ),
)
AGENT_ROUTE_MIGRATION_MATRIX: tuple[RouteMigrationEntry, ...] = (
    route(
        "/api/v1/agent/conversations",
        methods=("POST",),
        handler_names=("create_conversation",),
        source_refs=("whoopdata/api/agent_routes.py:16-25",),
        canonical_surface="agent",
        target_path="/api/v1/agent/conversations",
        current_role="conversation",
        notes="Canonical public route for establishing or resuming a user-facing conversation handle.",
    ),
    route(
        "/api/v1/agent/messages",
        methods=("POST",),
        handler_names=("send_message",),
        source_refs=("whoopdata/api/agent_routes.py:28-40",),
        canonical_surface="agent",
        target_path="/api/v1/agent/messages",
        current_role="conversation",
        notes="Canonical public route for submitting user messages through the shared conversation boundary.",
    ),
)


DATA_ROUTE_MIGRATION_MATRIX: tuple[RouteMigrationEntry, ...] = (
    route(
        "/api/v1/data/recovery",
        handler_names=("get_recovery_data",),
        source_refs=("whoopdata/api/recovery_routes.py:13-59",),
        canonical_surface="data",
        target_path="/api/v1/data/recovery",
    ),
    route(
        "/api/v1/data/workouts",
        handler_names=("get_workout_data",),
        source_refs=("whoopdata/api/workout_routes.py:35-81",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts",
    ),
    route(
        "/api/v1/data/workouts/types/running",
        handler_names=("get_running_workouts",),
        source_refs=("whoopdata/api/workout_routes.py:84-118",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts/types/running",
    ),
    route(
        "/api/v1/data/workouts/types/tennis",
        handler_names=("get_tennis_workouts",),
        source_refs=("whoopdata/api/workout_routes.py:122-156",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts/types/tennis",
    ),
    route(
        "/api/v1/data/sleep",
        handler_names=("get_sleep_data",),
        source_refs=("whoopdata/api/sleep_routes.py:12-51",),
        canonical_surface="data",
        target_path="/api/v1/data/sleep",
    ),
    route(
        "/api/v1/data/withings/weight",
        handler_names=("get_weight_data",),
        source_refs=("whoopdata/api/withings_routes.py:13-104",),
        canonical_surface="data",
        target_path="/api/v1/data/withings/weight",
    ),
    route(
        "/api/v1/data/withings/heart-rate",
        handler_names=("get_heart_rate_data",),
        source_refs=("whoopdata/api/withings_routes.py:202-273",),
        canonical_surface="data",
        target_path="/api/v1/data/withings/heart-rate",
    ),
    route(
        "/api/v1/data/integrations/withings/status",
        handler_names=("withings_status",),
        source_refs=("whoopdata/api/withings_status_routes.py:12-51",),
        canonical_surface="data",
        target_path="/api/v1/data/integrations/withings/status",
        current_role="integration_status",
    ),
    route(
        "/api/v1/data/weather/current",
        handler_names=("get_current_weather",),
        source_refs=("whoopdata/api/weather_routes.py:18-52",),
        canonical_surface="data",
        target_path="/api/v1/data/weather/current",
    ),
    route(
        "/api/v1/data/weather/forecast",
        handler_names=("get_weather_forecast",),
        source_refs=("whoopdata/api/weather_routes.py:57-98",),
        canonical_surface="data",
        target_path="/api/v1/data/weather/forecast",
    ),
    route(
        "/api/v1/data/weather/air-quality",
        handler_names=("get_air_quality",),
        source_refs=("whoopdata/api/weather_routes.py:103-136",),
        canonical_surface="data",
        target_path="/api/v1/data/weather/air-quality",
    ),
    route(
        "/api/v1/data/transport/status",
        handler_names=("get_transport_status",),
        source_refs=("whoopdata/api/transport_routes.py:13-31",),
        canonical_surface="data",
        target_path="/api/v1/data/transport/status",
    ),
    route(
        "/api/v1/data/transport/arrivals",
        handler_names=("get_train_arrivals",),
        source_refs=("whoopdata/api/transport_routes.py:36-55",),
        canonical_surface="data",
        target_path="/api/v1/data/transport/arrivals",
    ),
    route(
        "/api/v1/data/tides/stations",
        handler_names=("list_stations",),
        source_refs=("whoopdata/api/tide_routes.py:16-42",),
        canonical_surface="data",
        target_path="/api/v1/data/tides/stations",
    ),
    route(
        "/api/v1/data/tides/current",
        handler_names=("get_current_tide",),
        source_refs=("whoopdata/api/tide_routes.py:46-67",),
        canonical_surface="data",
        target_path="/api/v1/data/tides/current",
    ),
    route(
        "/api/v1/data/tides/station/{station_id}",
        handler_names=("get_station_info",),
        source_refs=("whoopdata/api/tide_routes.py:221-242",),
        canonical_surface="data",
        target_path="/api/v1/data/tides/station/{station_id}",
    ),
    route(
        "/recovery",
        handler_names=("get_recovery_data",),
        source_refs=("whoopdata/api/recovery_routes.py:13-59",),
        canonical_surface="data",
        target_path="/api/v1/data/recovery",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
        notes="Legacy raw-data route retained as a deprecated compatibility adapter.",
    ),
    route(
        "/recoveries/",
        handler_names=("list_recoveries_compat",),
        source_refs=("whoopdata/api/recovery_routes.py:89-92",),
        canonical_surface="data",
        target_path="/api/v1/data/recovery",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
        notes="Existing website compatibility alias for the canonical recovery resource.",
    ),
    route(
        "/recovery/latest",
        handler_names=("latest_recovery_compat",),
        source_refs=("whoopdata/api/recovery_routes.py:95-101",),
        canonical_surface="data",
        target_path="/api/v1/data/recovery?latest=true",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/recoveries/top",
        handler_names=("top_recoveries_compat",),
        source_refs=("whoopdata/api/recovery_routes.py:104-107",),
        canonical_surface="data",
        target_path="/api/v1/data/recovery?top=true",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/workouts",
        handler_names=("get_workout_data",),
        source_refs=("whoopdata/api/workout_routes.py:35-81",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
        notes="Legacy raw-data route retained as a deprecated compatibility adapter.",
    ),
    route(
        "/workouts/types/running",
        handler_names=("get_running_workouts",),
        source_refs=("whoopdata/api/workout_routes.py:84-118",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts/types/running",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/workouts/types/tennis",
        handler_names=("get_tennis_workouts",),
        source_refs=("whoopdata/api/workout_routes.py:122-156",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts/types/tennis",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/workouts/",
        handler_names=("list_workouts_compat",),
        source_refs=("whoopdata/api/workout_routes.py:195-198",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
        notes="Existing website compatibility alias for the canonical workouts resource.",
    ),
    route(
        "/workouts/latest",
        handler_names=("latest_workout_compat",),
        source_refs=("whoopdata/api/workout_routes.py:201-207",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts?latest=true",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/workouts/get_runs",
        handler_names=("list_runs_compat",),
        source_refs=("whoopdata/api/workout_routes.py:210-213",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts/types/running",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/workouts/get_tennis",
        handler_names=("list_tennis_compat",),
        source_refs=("whoopdata/api/workout_routes.py:228-231",),
        canonical_surface="data",
        target_path="/api/v1/data/workouts/types/tennis",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/sleep",
        handler_names=("get_sleep_data",),
        source_refs=("whoopdata/api/sleep_routes.py:13-52",),
        canonical_surface="data",
        target_path="/api/v1/data/sleep",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
        notes="Legacy raw-data route retained as a deprecated compatibility adapter.",
    ),
    route(
        "/sleep/",
        handler_names=("list_sleep_compat",),
        source_refs=("whoopdata/api/sleep_routes.py:61-64",),
        canonical_surface="data",
        target_path="/api/v1/data/sleep",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/sleep/latest",
        handler_names=("latest_sleep_compat",),
        source_refs=("whoopdata/api/sleep_routes.py:67-73",),
        canonical_surface="data",
        target_path="/api/v1/data/sleep?latest=true",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/withings/weight",
        handler_names=("get_weight_data",),
        source_refs=("whoopdata/api/withings_routes.py:13-104",),
        canonical_surface="data",
        target_path="/api/v1/data/withings/weight",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
        notes="Legacy raw-data route retained as a deprecated compatibility adapter.",
    ),
    route(
        "/withings/weight/latest",
        handler_names=("get_latest_weight",),
        source_refs=("whoopdata/api/withings_routes.py:109-142",),
        canonical_surface="data",
        target_path="/api/v1/data/withings/weight?latest=true",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/withings/heart-rate",
        handler_names=("get_heart_rate_data",),
        source_refs=("whoopdata/api/withings_routes.py:202-273",),
        canonical_surface="data",
        target_path="/api/v1/data/withings/heart-rate",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
        notes="Legacy raw-data route retained as a deprecated compatibility adapter.",
    ),
    route(
        "/withings/heart-rate/latest",
        handler_names=("get_latest_heart_rate",),
        source_refs=("whoopdata/api/withings_routes.py:279-308",),
        canonical_surface="data",
        target_path="/api/v1/data/withings/heart-rate?latest=true",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/auth/withings/status",
        handler_names=("withings_status",),
        source_refs=("whoopdata/api/withings_status_routes.py:12-51",),
        canonical_surface="data",
        target_path="/api/v1/data/integrations/withings/status",
        current_role="integration_status",
        migration_action="keep_temporary_adapter",
        notes="Legacy integration-status path retained as a deprecated compatibility adapter.",
    ),
    route(
        "/weather/current",
        handler_names=("get_current_weather",),
        source_refs=("whoopdata/api/weather_routes.py:18-52",),
        canonical_surface="data",
        target_path="/api/v1/data/weather/current",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/weather/forecast",
        handler_names=("get_weather_forecast",),
        source_refs=("whoopdata/api/weather_routes.py:57-98",),
        canonical_surface="data",
        target_path="/api/v1/data/weather/forecast",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/weather/air-quality",
        handler_names=("get_air_quality",),
        source_refs=("whoopdata/api/weather_routes.py:103-136",),
        canonical_surface="data",
        target_path="/api/v1/data/weather/air-quality",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/transport/status",
        handler_names=("get_transport_status",),
        source_refs=("whoopdata/api/transport_routes.py:13-31",),
        canonical_surface="data",
        target_path="/api/v1/data/transport/status",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/transport/arrivals",
        handler_names=("get_train_arrivals",),
        source_refs=("whoopdata/api/transport_routes.py:36-55",),
        canonical_surface="data",
        target_path="/api/v1/data/transport/arrivals",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/tides/stations",
        handler_names=("list_stations",),
        source_refs=("whoopdata/api/tide_routes.py:17-42",),
        canonical_surface="data",
        target_path="/api/v1/data/tides/stations",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/tides/current",
        handler_names=("get_current_tide",),
        source_refs=("whoopdata/api/tide_routes.py:47-67",),
        canonical_surface="data",
        target_path="/api/v1/data/tides/current",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/tides/station/{station_id}",
        handler_names=("get_station_info",),
        source_refs=("whoopdata/api/tide_routes.py:222-242",),
        canonical_surface="data",
        target_path="/api/v1/data/tides/station/{station_id}",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
)


INSIGHT_ROUTE_MIGRATION_MATRIX: tuple[RouteMigrationEntry, ...] = (
    route(
        "/api/v1/insights/recovery/analytics/weekly",
        handler_names=("get_recovery_weekly_analytics",),
        source_refs=("whoopdata/api/recovery_routes.py:65-82",),
        canonical_surface="insights",
        target_path="/api/v1/insights/recovery/analytics/weekly",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/workouts/analytics/trimp",
        handler_names=("get_running_workouts_with_trimp",),
        source_refs=("whoopdata/api/workout_routes.py:163-188",),
        canonical_surface="insights",
        target_path="/api/v1/insights/workouts/analytics/trimp",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/withings/weight/analytics",
        handler_names=("get_weight_stats",),
        source_refs=("whoopdata/api/withings_routes.py:147-203",),
        canonical_surface="insights",
        target_path="/api/v1/insights/withings/weight/analytics",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/withings/summary",
        handler_names=("get_withings_summary",),
        source_refs=("whoopdata/api/withings_routes.py:315-374",),
        canonical_surface="insights",
        target_path="/api/v1/insights/withings/summary",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/dashboard/daily",
        handler_names=("get_daily_dashboard",),
        source_refs=("whoopdata/api/dashboard_routes.py:14-39",),
        canonical_surface="insights",
        target_path="/api/v1/insights/dashboard/daily",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/dashboard/health-metrics",
        handler_names=("get_health_metrics",),
        source_refs=("whoopdata/api/dashboard_routes.py:42-67",),
        canonical_surface="insights",
        target_path="/api/v1/insights/dashboard/health-metrics",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/dashboard/weather-extended",
        handler_names=("get_weather_extended",),
        source_refs=("whoopdata/api/dashboard_routes.py:70-95",),
        canonical_surface="insights",
        target_path="/api/v1/insights/dashboard/weather-extended",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/recovery/factors",
        handler_names=("analyze_recovery_factors",),
        source_refs=("whoopdata/api/analytics_routes.py:44-76",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/factors",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/sleep/factors",
        handler_names=("analyze_sleep_quality_factors",),
        source_refs=("whoopdata/api/analytics_routes.py:79-115",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/sleep/factors",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/correlations",
        handler_names=("analyze_correlations",),
        source_refs=("whoopdata/api/analytics_routes.py:118-148",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/correlations",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/predict/recovery",
        methods=("POST",),
        handler_names=("predict_recovery",),
        source_refs=("whoopdata/api/analytics_routes.py:152-220",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/predict/recovery",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/predict/sleep",
        methods=("POST",),
        handler_names=("predict_sleep_performance",),
        source_refs=("whoopdata/api/analytics_routes.py:224-261",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/predict/sleep",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/insights/weekly",
        handler_names=("get_weekly_insights",),
        source_refs=("whoopdata/api/analytics_routes.py:265-297",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/insights/weekly",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/patterns/{metric}",
        handler_names=("analyze_metric_pattern",),
        source_refs=("whoopdata/api/analytics_routes.py:301-349",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/patterns/{metric}",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/recovery/deep-dive",
        handler_names=("get_recovery_deep_dive",),
        source_refs=("whoopdata/api/analytics_routes.py:352-385",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/deep-dive",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/recovery/by-sport",
        handler_names=("get_recovery_by_sport",),
        source_refs=("whoopdata/api/analytics_routes.py:388-412",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/by-sport",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/recovery/by-time-of-day",
        handler_names=("get_recovery_by_time_of_day",),
        source_refs=("whoopdata/api/analytics_routes.py:415-440",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/by-time-of-day",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/recovery/by-hr-zones",
        handler_names=("get_recovery_by_hr_zones",),
        source_refs=("whoopdata/api/analytics_routes.py:444-468",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/by-hr-zones",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/recovery/strain-patterns",
        handler_names=("get_strain_patterns",),
        source_refs=("whoopdata/api/analytics_routes.py:473-495",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/strain-patterns",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/summary",
        handler_names=("get_analytics_summary",),
        source_refs=("whoopdata/api/analytics_routes.py:500-532",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/summary",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/recovery/mlr",
        handler_names=("get_recovery_mlr",),
        source_refs=("whoopdata/api/analytics_routes.py:536-560",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/mlr",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/hrv/mlr",
        handler_names=("get_hrv_mlr",),
        source_refs=("whoopdata/api/analytics_routes.py:565-589",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/hrv/mlr",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/analytics/correlations/matrix",
        handler_names=("get_correlation_matrix",),
        source_refs=("whoopdata/api/analytics_routes.py:594-618",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/correlations/matrix",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/tides/forecast",
        handler_names=("get_tide_forecast",),
        source_refs=("whoopdata/api/tide_routes.py:73-108",),
        canonical_surface="insights",
        target_path="/api/v1/insights/tides/forecast",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/tides/stats",
        handler_names=("get_tidal_statistics",),
        source_refs=("whoopdata/api/tide_routes.py:111-134",),
        canonical_surface="insights",
        target_path="/api/v1/insights/tides/stats",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/tides/optimal-walk",
        handler_names=("get_optimal_walk_times",),
        source_refs=("whoopdata/api/tide_routes.py:137-220",),
        canonical_surface="insights",
        target_path="/api/v1/insights/tides/optimal-walk",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/daily-plan",
        handler_names=("get_daily_plan",),
        source_refs=("whoopdata/api/daily_routes.py:29-49",),
        canonical_surface="insights",
        target_path="/api/v1/insights/daily-plan",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/scenarios/recovery",
        methods=("POST",),
        handler_names=("predict_scenario",),
        source_refs=("whoopdata/api/daily_routes.py:52-73",),
        canonical_surface="insights",
        target_path="/api/v1/insights/scenarios/recovery",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/scenarios/compare",
        methods=("POST",),
        handler_names=("compare_scenarios",),
        source_refs=("whoopdata/api/daily_routes.py:76-96",),
        canonical_surface="insights",
        target_path="/api/v1/insights/scenarios/compare",
        current_role="derived_output",
    ),
    route(
        "/api/v1/insights/reports/weekly",
        handler_names=("get_weekly_coaching_report",),
        source_refs=("whoopdata/api/daily_routes.py:99-119",),
        canonical_surface="insights",
        target_path="/api/v1/insights/reports/weekly",
        current_role="derived_output",
    ),
    route(
        "/recovery/analytics/weekly",
        handler_names=("get_recovery_weekly_analytics",),
        source_refs=("whoopdata/api/recovery_routes.py:65-82",),
        canonical_surface="insights",
        target_path="/api/v1/insights/recovery/analytics/weekly",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/recoveries/avg_recoveries/",
        handler_names=("avg_recovery_compat",),
        source_refs=("whoopdata/api/recovery_routes.py:112-115",),
        canonical_surface="insights",
        target_path="/api/v1/insights/recovery/analytics/weekly",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/workouts/analytics/trimp",
        handler_names=("get_running_workouts_with_trimp",),
        source_refs=("whoopdata/api/workout_routes.py:163-188",),
        canonical_surface="insights",
        target_path="/api/v1/insights/workouts/analytics/trimp",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/workouts/get_run_trimp",
        handler_names=("list_trimp_scores_compat",),
        source_refs=("whoopdata/api/workout_routes.py:218-228",),
        canonical_surface="insights",
        target_path="/api/v1/insights/workouts/analytics/trimp",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/withings/weight/analytics",
        handler_names=("get_weight_stats",),
        source_refs=("whoopdata/api/withings_routes.py:147-203",),
        canonical_surface="insights",
        target_path="/api/v1/insights/withings/weight/analytics",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/withings/weight/stats",
        handler_names=("get_weight_stats_compat",),
        source_refs=("whoopdata/api/withings_routes.py:383-436",),
        canonical_surface="insights",
        target_path="/api/v1/insights/withings/weight/analytics",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/withings/summary",
        handler_names=("get_withings_summary",),
        source_refs=("whoopdata/api/withings_routes.py:315-374",),
        canonical_surface="insights",
        target_path="/api/v1/insights/withings/summary",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/dashboard/daily",
        handler_names=("get_daily_dashboard",),
        source_refs=("whoopdata/api/dashboard_routes.py:14-39",),
        canonical_surface="insights",
        target_path="/api/v1/insights/dashboard/daily",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/dashboard/health-metrics",
        handler_names=("get_health_metrics",),
        source_refs=("whoopdata/api/dashboard_routes.py:42-67",),
        canonical_surface="insights",
        target_path="/api/v1/insights/dashboard/health-metrics",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/dashboard/weather-extended",
        handler_names=("get_weather_extended",),
        source_refs=("whoopdata/api/dashboard_routes.py:70-95",),
        canonical_surface="insights",
        target_path="/api/v1/insights/dashboard/weather-extended",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/recovery/factors",
        handler_names=("analyze_recovery_factors",),
        source_refs=("whoopdata/api/analytics_routes.py:44-76",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/factors",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/sleep/factors",
        handler_names=("analyze_sleep_quality_factors",),
        source_refs=("whoopdata/api/analytics_routes.py:79-115",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/sleep/factors",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/correlations",
        handler_names=("analyze_correlations",),
        source_refs=("whoopdata/api/analytics_routes.py:118-148",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/correlations",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/predict/recovery",
        methods=("POST",),
        handler_names=("predict_recovery",),
        source_refs=("whoopdata/api/analytics_routes.py:152-220",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/predict/recovery",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/predict/sleep",
        methods=("POST",),
        handler_names=("predict_sleep_performance",),
        source_refs=("whoopdata/api/analytics_routes.py:224-261",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/predict/sleep",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/insights/weekly",
        handler_names=("get_weekly_insights",),
        source_refs=("whoopdata/api/analytics_routes.py:265-297",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/insights/weekly",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/patterns/{metric}",
        handler_names=("analyze_metric_pattern",),
        source_refs=("whoopdata/api/analytics_routes.py:301-349",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/patterns/{metric}",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/recovery/deep-dive",
        handler_names=("get_recovery_deep_dive",),
        source_refs=("whoopdata/api/analytics_routes.py:352-385",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/deep-dive",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/recovery/by-sport",
        handler_names=("get_recovery_by_sport",),
        source_refs=("whoopdata/api/analytics_routes.py:388-412",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/by-sport",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/recovery/by-time-of-day",
        handler_names=("get_recovery_by_time_of_day",),
        source_refs=("whoopdata/api/analytics_routes.py:415-440",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/by-time-of-day",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/recovery/by-hr-zones",
        handler_names=("get_recovery_by_hr_zones",),
        source_refs=("whoopdata/api/analytics_routes.py:444-468",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/by-hr-zones",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/recovery/strain-patterns",
        handler_names=("get_strain_patterns",),
        source_refs=("whoopdata/api/analytics_routes.py:473-495",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/strain-patterns",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/summary",
        handler_names=("get_analytics_summary",),
        source_refs=("whoopdata/api/analytics_routes.py:500-532",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/summary",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/recovery/mlr",
        handler_names=("get_recovery_mlr",),
        source_refs=("whoopdata/api/analytics_routes.py:536-560",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/recovery/mlr",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/hrv/mlr",
        handler_names=("get_hrv_mlr",),
        source_refs=("whoopdata/api/analytics_routes.py:565-589",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/hrv/mlr",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/analytics/correlations/matrix",
        handler_names=("get_correlation_matrix",),
        source_refs=("whoopdata/api/analytics_routes.py:594-618",),
        canonical_surface="insights",
        target_path="/api/v1/insights/analytics/correlations/matrix",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/tides/forecast",
        handler_names=("get_tide_forecast",),
        source_refs=("whoopdata/api/tide_routes.py:73-108",),
        canonical_surface="insights",
        target_path="/api/v1/insights/tides/forecast",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/tides/stats",
        handler_names=("get_tidal_statistics",),
        source_refs=("whoopdata/api/tide_routes.py:111-134",),
        canonical_surface="insights",
        target_path="/api/v1/insights/tides/stats",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/tides/optimal-walk",
        handler_names=("get_optimal_walk_times",),
        source_refs=("whoopdata/api/tide_routes.py:137-220",),
        canonical_surface="insights",
        target_path="/api/v1/insights/tides/optimal-walk",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/api/daily-plan",
        handler_names=("get_daily_plan",),
        source_refs=("whoopdata/api/daily_routes.py:29-49",),
        canonical_surface="insights",
        target_path="/api/v1/insights/daily-plan",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/api/scenarios/recovery",
        methods=("POST",),
        handler_names=("predict_scenario",),
        source_refs=("whoopdata/api/daily_routes.py:52-73",),
        canonical_surface="insights",
        target_path="/api/v1/insights/scenarios/recovery",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/api/scenarios/compare",
        methods=("POST",),
        handler_names=("compare_scenarios",),
        source_refs=("whoopdata/api/daily_routes.py:76-96",),
        canonical_surface="insights",
        target_path="/api/v1/insights/scenarios/compare",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
    route(
        "/api/reports/weekly",
        handler_names=("get_weekly_coaching_report",),
        source_refs=("whoopdata/api/daily_routes.py:99-119",),
        canonical_surface="insights",
        target_path="/api/v1/insights/reports/weekly",
        current_role="legacy_alias",
        migration_action="keep_temporary_adapter",
    ),
)


ROUTE_MIGRATION_MATRIX: tuple[RouteMigrationEntry, ...] = (
    WEB_ROUTE_MIGRATION_MATRIX
    + DATA_ROUTE_MIGRATION_MATRIX
    + INSIGHT_ROUTE_MIGRATION_MATRIX
    + AGENT_ROUTE_MIGRATION_MATRIX
)


ENTRYPOINT_MIGRATION_MATRIX: tuple[EntrypointMigrationEntry, ...] = (
    entrypoint(
        "whoop-start",
        kind="project_script",
        source_refs=("pyproject.toml:90-93", "whoopdata/cli.py:274-399"),
        current_role="combined_launcher",
        primary_surface="mixed",
        target="Split into explicit ingest, API, and analytics lanes; keep only as a convenience wrapper.",
        migration_action="keep_convenience_only",
        notes="Current interactive menu mixes ETL, API startup, and analytics execution in one entrypoint.",
    ),
    entrypoint(
        "whoop-etl",
        kind="project_script",
        source_refs=("pyproject.toml:90-93", "whoopdata/etl.py:1-999"),
        current_role="etl",
        primary_surface="data",
        target="Canonical ingestion script for populating the data surface.",
        migration_action="keep_primary",
    ),
    entrypoint(
        "whoop-withings-auth",
        kind="project_script",
        source_refs=("pyproject.toml:90-93", "whoopdata/cli.py:257-272"),
        current_role="provider_auth",
        primary_surface="data",
        target="Canonical provider-auth utility for the Withings integration.",
        migration_action="keep_primary",
    ),
    entrypoint(
        "run",
        kind="make_target",
        source_refs=("Makefile:49-52", "whoopdata/cli.py:274-399"),
        current_role="combined_launcher",
        primary_surface="mixed",
        target="Convenience wrapper around the split ingest, API, and analytics lanes.",
        migration_action="keep_convenience_only",
    ),
    entrypoint(
        "server",
        kind="make_target",
        source_refs=("Makefile:53-56", "main.py:1-4", "whoopdata/api/app_factory.py:1-106"),
        current_role="api_server",
        primary_surface="mixed",
        target="Canonical FastAPI server command for the web, data, insights, and agent surfaces.",
        migration_action="keep_primary",
    ),
    entrypoint(
        "etl",
        kind="make_target",
        source_refs=("Makefile:57-60",),
        current_role="etl",
        primary_surface="data",
        target="Canonical incremental ingestion command.",
        migration_action="keep_primary",
    ),
    entrypoint(
        "etl-full",
        kind="make_target",
        source_refs=("Makefile:61-63",),
        current_role="etl",
        primary_surface="data",
        target="Canonical full-history ingestion command.",
        migration_action="keep_primary",
    ),
    entrypoint(
        "chat",
        kind="make_target",
        source_refs=("Makefile:65-67", "chat_app.py:32-136", "chat_app.py:278-293"),
        current_role="chat_ui",
        primary_surface="agent",
        target="Gradio UI backed by the shared /api/v1/agent/* conversation boundary.",
        migration_action="consolidate_under_agent_surface",
        notes="Current chat UI now reuses the shared conversation service and boundary-owned session/thread IDs from the canonical agent surface.",
    ),
    entrypoint(
        "analytics",
        kind="make_target",
        source_refs=("Makefile:69-71", "whoopdata/cli.py:237-254"),
        current_role="analytics_job",
        primary_surface="insights",
        target="Canonical analytics materialization command for pre-computed insights.",
        migration_action="keep_primary",
    ),
    entrypoint(
        "langgraph-dev",
        kind="make_target",
        source_refs=("Makefile:73-77", "langgraph.json:5-10"),
        current_role="graph_dev",
        primary_surface="agent",
        target="Development-only LangGraph tooling behind the public /api/v1/agent/* surface.",
        migration_action="keep_dev_only",
    ),
    entrypoint(
        "dev-all",
        kind="make_target",
        source_refs=("Makefile:79-86",),
        current_role="combined_launcher",
        primary_surface="mixed",
        target="Convenience wrapper for make server + make langgraph-dev.",
        migration_action="keep_convenience_only",
    ),
    entrypoint(
        "chat_app.py",
        kind="python_script",
        source_refs=("chat_app.py:32-136", "chat_app.py:278-293"),
        current_role="chat_ui",
        primary_surface="agent",
        target="Shared conversation service that fronts /api/v1/agent/* for the Gradio UI.",
        migration_action="consolidate_under_agent_surface",
        notes="Current implementation reuses the shared conversation service directly so the Gradio UI and API surface share the same session/thread ownership model.",
    ),
    entrypoint(
        "health_agent",
        kind="langgraph_graph",
        source_refs=("langgraph.json:5-10",),
        current_role="graph_dev",
        primary_surface="agent",
        target="Internal graph exposed through dev tooling and the future /api/v1/agent/* boundary.",
        migration_action="keep_dev_only",
        notes="Current graph exposure is separate from FastAPI and not yet a first-class product API.",
    ),
)
