#!/usr/bin/env python3
"""
WHOOP Data Platform - First-time setup wizard.

Guides new users through creating their .env file, validating credentials,
and initialising the database so they can run their first ETL in minutes.
"""

import os
import sys
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.rule import Rule
from rich.table import Table

console = Console()

ENV_PATH = Path(".env")
ENV_EXAMPLE_PATH = Path(".env.example")

# ── credential definitions ────────────────────────────────────────────────────

REQUIRED_CREDENTIALS = [
    {
        "key": "WHOOP_CLIENT_ID",
        "label": "WHOOP Client ID",
        "secret": False,
        "hint": "From https://developer.whoop.com/ → Applications → your app → Client ID",
    },
    {
        "key": "WHOOP_CLIENT_SECRET",
        "label": "WHOOP Client Secret",
        "secret": True,
        "hint": "From the same WHOOP developer dashboard (keep this private)",
    },
    {
        "key": "WITHINGS_CLIENT_ID",
        "label": "Withings Client ID",
        "secret": False,
        "hint": "From https://account.withings.com/partner/dashboard_oauth2",
    },
    {
        "key": "WITHINGS_CLIENT_SECRET",
        "label": "Withings Client Secret",
        "secret": True,
        "hint": "From the same Withings partner dashboard (keep this private)",
    },
    {
        "key": "OPENAI_API_KEY",
        "label": "OpenAI API Key",
        "secret": True,
        "hint": "From https://platform.openai.com/api-keys",
    },
]

OPTIONAL_CREDENTIALS = [
    {
        "key": "OPENWEATHER_API_KEY",
        "label": "OpenWeatherMap API Key (optional)",
        "secret": True,
        "hint": "From https://openweathermap.org/api — used for weather context in coaching",
    },
    {
        "key": "TELEGRAM_BOT_TOKEN",
        "label": "Telegram Bot Token (optional)",
        "secret": True,
        "hint": "Create a bot via @BotFather on Telegram and paste the token here",
    },
]

FIXED_VALUES = {
    "WITHINGS_CALLBACK_URL": "http://localhost:8766/callback",
}


# ── helpers ───────────────────────────────────────────────────────────────────


def _load_existing_env() -> dict[str, str]:
    """Return key→value pairs from the existing .env (if present)."""
    values: dict[str, str] = {}
    if not ENV_PATH.exists():
        return values
    with open(ENV_PATH) as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, _, v = line.partition("=")
                values[k.strip()] = v.strip()
    return values


def _prompt_credential(cred: dict, existing: str = "") -> str:
    """Interactively prompt the user for a single credential."""
    console.print(f"\n[bold cyan]{cred['label']}[/bold cyan]")
    console.print(f"[dim]{cred['hint']}[/dim]")

    placeholder = ""
    if existing:
        if cred["secret"]:
            placeholder = existing[:4] + "****" + existing[-4:] if len(existing) > 8 else "****"
        else:
            placeholder = existing

    prompt_text = f"  Enter value{f' [{placeholder}]' if placeholder else ''}"

    if cred["secret"]:
        value = Prompt.ask(prompt_text, password=True, default=existing)
    else:
        value = Prompt.ask(prompt_text, default=existing)

    return value.strip()


def _write_env(values: dict[str, str]) -> None:
    """Write all collected values to .env, preserving comment structure."""
    sections = [
        ("# WHOOP API Configuration", ["WHOOP_CLIENT_ID", "WHOOP_CLIENT_SECRET"]),
        (
            "# Withings API Configuration",
            ["WITHINGS_CLIENT_ID", "WITHINGS_CLIENT_SECRET", "WITHINGS_CALLBACK_URL"],
        ),
        ("# OpenAI API Configuration", ["OPENAI_API_KEY"]),
        ("# Weather API Configuration (optional)", ["OPENWEATHER_API_KEY"]),
        ("# Telegram Bot Configuration (optional)", ["TELEGRAM_BOT_TOKEN"]),
    ]

    lines = ["# WHOOP Data Platform — generated by whoop-setup", ""]
    for comment, keys in sections:
        lines.append(comment)
        for key in keys:
            val = values.get(key, "")
            if val:
                lines.append(f"{key}={val}")
        lines.append("")

    # Append any extra keys that were in the original file but not covered above
    covered = {k for _, keys in sections for k in keys}
    extras = {k: v for k, v in values.items() if k not in covered}
    if extras:
        lines.append("# Additional settings")
        for k, v in extras.items():
            lines.append(f"{k}={v}")
        lines.append("")

    ENV_PATH.write_text("\n".join(lines))
    console.print(f"\n✅ [bold green].env written to {ENV_PATH.resolve()}[/bold green]")


def _setup_database() -> bool:
    """Create SQLite database tables."""
    console.print("\n[bold]Initialising database tables...[/bold]")
    try:
        # Load env so the database URL is resolved before importing
        from dotenv import load_dotenv

        load_dotenv(ENV_PATH)

        from whoopdata.database.database import engine
        from whoopdata.models.models import Base

        Base.metadata.create_all(bind=engine)
        console.print("✅ [bold green]Database tables ready[/bold green]")
        return True
    except Exception as exc:
        console.print(f"❌ [bold red]Database setup failed:[/bold red] {exc}")
        console.print("[dim]You can retry later with: make etl[/dim]")
        return False


def _show_next_steps() -> None:
    """Print a summary of recommended next actions."""
    console.print()
    console.print(Rule("[bold magenta]You're all set![/bold magenta]"))

    table = Table(show_header=True, header_style="bold magenta", box=None)
    table.add_column("Step", style="bold cyan", no_wrap=True)
    table.add_column("Command", style="green")
    table.add_column("What it does")

    table.add_row("1", "make etl", "Fetch data from WHOOP and Withings (incremental)")
    table.add_row("2", "make server", "Start the FastAPI server at http://localhost:8000")
    table.add_row("3", "make chat", "Open the chat UI at http://localhost:7860 (optional)")
    table.add_row("4", "make analytics", "Train ML models and materialise insights (optional)")
    table.add_row("5", "make verify", "Run a full system health check at any time")

    console.print(table)
    console.print()
    console.print(
        Panel.fit(
            "[dim]WHOOP uses OAuth 2.0. The first time you run [bold]make etl[/bold] you will "
            "be redirected to your browser to complete the authorisation flow.[/dim]",
            title="[bold yellow]Note[/bold yellow]",
        )
    )


# ── main entry point ──────────────────────────────────────────────────────────


def main() -> int:
    """Interactive first-time setup wizard for the WHOOP Data Platform."""
    console.print(
        Panel.fit(
            "[bold]WHOOP Data Platform — Setup Wizard[/bold]\n\n"
            "[dim]This wizard will create your [bold].env[/bold] file with API credentials\n"
            "and initialise the local database so you are ready to ingest data.[/dim]",
            style="bold magenta",
        )
    )

    # ── check for an existing .env ─────────────────────────────────────────
    existing = _load_existing_env()
    if existing:
        console.print(
            f"\n[bold yellow]A .env file already exists[/bold yellow] at {ENV_PATH.resolve()}"
        )
        if not Confirm.ask("  Re-run setup and update credentials?", default=False):
            console.print("[dim]Setup cancelled — your existing .env was not modified.[/dim]")
            return 0

    values: dict[str, str] = dict(existing)

    # ── fixed values ───────────────────────────────────────────────────────
    for key, val in FIXED_VALUES.items():
        values[key] = val

    # ── required credentials ───────────────────────────────────────────────
    console.print()
    console.print(Rule("[bold cyan]Required credentials[/bold cyan]"))

    for cred in REQUIRED_CREDENTIALS:
        value = _prompt_credential(cred, existing=existing.get(cred["key"], ""))
        if not value:
            console.print(
                f"[bold red]  ✗ {cred['label']} is required — setup aborted.[/bold red]"
            )
            return 1
        values[cred["key"]] = value

    # ── optional credentials ───────────────────────────────────────────────
    console.print()
    console.print(Rule("[bold cyan]Optional credentials[/bold cyan]"))
    console.print("[dim]Press Enter to skip any optional credential.[/dim]")

    for cred in OPTIONAL_CREDENTIALS:
        current = existing.get(cred["key"], "")
        if cred["secret"]:
            value = Prompt.ask(
                f"\n[bold]{cred['label']}[/bold]\n  [dim]{cred['hint']}[/dim]\n  Value",
                password=True,
                default=current,
            )
        else:
            value = Prompt.ask(
                f"\n[bold]{cred['label']}[/bold]\n  [dim]{cred['hint']}[/dim]\n  Value",
                default=current,
            )
        if value.strip():
            values[cred["key"]] = value.strip()

    # ── write .env ─────────────────────────────────────────────────────────
    console.print()
    console.print(Rule("[bold cyan]Writing configuration[/bold cyan]"))
    _write_env(values)

    # ── database init ──────────────────────────────────────────────────────
    console.print()
    console.print(Rule("[bold cyan]Database initialisation[/bold cyan]"))
    _setup_database()

    # ── next steps ─────────────────────────────────────────────────────────
    _show_next_steps()

    return 0


if __name__ == "__main__":
    sys.exit(main())
