# Generated by Django 5.2.3 on 2025-06-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('timezone_offset', models.CharField(blank=True, max_length=50, null=True)),
                ('score_state', models.CharField(blank=True, max_length=50, null=True)),
                ('strain', models.FloatField(blank=True, null=True)),
                ('kilojoule', models.FloatField(blank=True, null=True)),
                ('average_heart_rate', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('timezone_offset', models.CharField(blank=True, max_length=50, null=True)),
                ('nap', models.BooleanField(default=False)),
                ('score_state', models.CharField(blank=True, max_length=50, null=True)),
                ('respiratory_rate', models.FloatField(blank=True, null=True)),
                ('sleep_performance_percentage', models.FloatField(blank=True, null=True)),
                ('sleep_consistency_percentage', models.FloatField(blank=True, null=True)),
                ('sleep_efficiency_percentage', models.FloatField(blank=True, null=True)),
                ('total_time_in_bed_time_milli', models.IntegerField(blank=True, null=True)),
                ('total_awake_time_milli', models.IntegerField(blank=True, null=True)),
                ('total_no_data_time_milli', models.IntegerField(blank=True, null=True)),
                ('total_slow_wave_sleep_time_milli', models.IntegerField(blank=True, null=True)),
                ('total_rem_sleep_time_milli', models.IntegerField(blank=True, null=True)),
                ('sleep_cycle_count', models.IntegerField(blank=True, null=True)),
                ('disturbance_count', models.IntegerField(blank=True, null=True)),
                ('baseline_sleep_needed_milli', models.IntegerField(blank=True, null=True)),
                ('need_from_sleep_debt_milli', models.IntegerField(blank=True, null=True)),
                ('need_from_recent_strain_milli', models.IntegerField(blank=True, null=True)),
                ('need_from_recent_nap_milli', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_state', models.CharField(blank=True, max_length=50, null=True)),
                ('user_calibrating', models.BooleanField(default=False)),
                ('recovery_score', models.FloatField(blank=True, null=True)),
                ('resting_heart_rate', models.FloatField(blank=True, null=True)),
                ('hrv_rmssd_milli', models.FloatField(blank=True, null=True)),
                ('spo2_percentage', models.FloatField(blank=True, null=True)),
                ('skin_temp_celsius', models.FloatField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='api.cycle')),
                ('sleep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='api.sleep')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('timezone_offset', models.CharField(blank=True, max_length=50, null=True)),
                ('sport_id', models.IntegerField(blank=True, null=True)),
                ('score_state', models.CharField(blank=True, max_length=50, null=True)),
                ('strain', models.FloatField(blank=True, null=True)),
                ('average_heart_rate', models.FloatField(blank=True, null=True)),
                ('max_heart_rate', models.FloatField(blank=True, null=True)),
                ('kilojoule', models.FloatField(blank=True, null=True)),
                ('percent_recorded', models.FloatField(blank=True, null=True)),
                ('distance_meter', models.FloatField(blank=True, null=True)),
                ('altitude_gain_meter', models.FloatField(blank=True, null=True)),
                ('altitude_change_meter', models.FloatField(blank=True, null=True)),
                ('zone_zero_minutes', models.FloatField(blank=True, null=True)),
                ('zone_one_minutes', models.FloatField(blank=True, null=True)),
                ('zone_two_minutes', models.FloatField(blank=True, null=True)),
                ('zone_three_minutes', models.FloatField(blank=True, null=True)),
                ('zone_four_minutes', models.FloatField(blank=True, null=True)),
                ('zone_five_minutes', models.FloatField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.cycle')),
            ],
        ),
    ]
