from sqlalchemy.orm import Session
from whoopdata.models.models import Sleep


def get_sleep(db: Session, skip: int = 0, limit: int = 10):
    """Get sleep.

    Args:
        db: Input value for this routine.
        skip: Input value for this routine.
        limit: Input value for this routine.

    Returns:
        Result generated by this routine.

    Example:
        # Example usage
        result = get_sleep(db=..., skip=..., limit=...)
        _ = result

    """
    return db.query(Sleep).order_by(Sleep.created_at.desc()).offset(skip).limit(limit).all()
