"""LangGraph assembly for the health data agent.

Builds a supervisor agent using create_agent with specialist subagents
wrapped as tools. All user-visible responses come from the supervisor.
"""

from typing import Any

from langchain.agents import create_agent
from langchain_core.messages import HumanMessage
from langgraph.constants import CONFIG_KEY_CHECKPOINTER
from langgraph.graph import END, START, StateGraph
from .memory_tools import manage_memory, search_memory

from .prompts import SUPERVISOR_SYSTEM_PROMPT
from .safety_node import safety_node
from .schemas import AgentConfig, HealthAgentState, HealthContextSchema
from .model_config_loader import get_supervisor_model_config
from .model_factory import build_chat_model
from .specialists import build_specialist_tools

CONFIG_KEY_STORE = "__store"


def _dedupe_tools_by_name(tools: list[Any]) -> list[Any]:
    """ dedupe tools by name.

    Args:
        tools: Input value for this routine.

    Returns:
        Result generated by this routine.

    
    """
    seen: set[str] = set()
    deduped: list[Any] = []
    for tool in tools:
        name = getattr(tool, "name", None)
        if name and name in seen:
            continue
        if name:
            seen.add(name)
        deduped.append(tool)
    return deduped


def _resolve_checkpointer(
    config: dict[str, Any] | None,
) -> Any | None:
    """ resolve checkpointer.

    Args:
        config: Input value for this routine.

    Returns:
        Result generated by this routine.

    
    """
    if not isinstance(config, dict):
        return None
    configurable = config.get("configurable")
    if not isinstance(configurable, dict):
        return None
    return configurable.get(CONFIG_KEY_CHECKPOINTER)


def _resolve_store(
    config: dict[str, Any] | None,
) -> Any | None:
    """ resolve store.

    Args:
        config: Input value for this routine.

    Returns:
        Result generated by this routine.

    
    """
    if not isinstance(config, dict):
        return None
    configurable = config.get("configurable")
    if not isinstance(configurable, dict):
        return None
    return configurable.get(CONFIG_KEY_STORE)


def _create_graph(*, checkpointer: Any | None = None, store: Any | None = None):
    """Build the compiled health data agent graph.

    Creates a supervisor agent (via create_agent) that delegates to
    specialist subagents wrapped as tools. The supervisor always
    produces the final user-facing response.

    Returns:
        Compiled LangGraph graph ready for .invoke() / .ainvoke()
    """
    # Build specialist wrapper tools from registry
    specialist_tools = build_specialist_tools()

    # Supervisor gets specialist tools + memory tools for direct use
    all_tools = _dedupe_tools_by_name(
        specialist_tools
        + [
            search_memory,
            manage_memory,
        ]
    )

    # Create the supervisor agent. create_agent returns a compiled LangGraph
    # graph that handles the tool-calling loop internally. Persistence
    # (checkpointer/store) stays on the supervisor exactly as before; the config
    # (thread_id) propagates down to it when the outer graph is invoked, so
    # conversation persistence is unchanged.
    supervisor_model = build_chat_model(get_supervisor_model_config())
    graph_kwargs = {
        "model": supervisor_model,
        "tools": all_tools,
        "system_prompt": SUPERVISOR_SYSTEM_PROMPT,
        "name": "health_coach",
        "context_schema": HealthContextSchema,
    }
    if checkpointer is not None:
        graph_kwargs["checkpointer"] = checkpointer
    if store is not None:
        graph_kwargs["store"] = store

    agent = create_agent(**graph_kwargs)

    # Wrap the supervisor in an outer graph that runs the biomarker safety node
    # on the final assistant message: agent -> safety_node -> END. This sits
    # inside the compiled graph so BOTH user-facing surfaces inherit it — the
    # LangGraph/LangSmith UI (loads the graph directly) and Telegram (calls the
    # same graph via ConversationService). See whoopdata/agent/safety_node.py.
    builder = StateGraph(HealthAgentState, context_schema=HealthContextSchema)
    builder.add_node("agent", agent)
    builder.add_node("safety_node", safety_node)
    builder.add_edge(START, "agent")
    builder.add_edge("agent", "safety_node")
    builder.add_edge("safety_node", END)

    return builder.compile()


def build_graph(config: dict[str, Any] | None = None):
    """Build the health data agent graph from a LangGraph config.

    This factory intentionally exposes a single positional config
    argument because LangGraph validates graph factory signatures while
    loading `langgraph.json`.

    Returns:
        Compiled LangGraph graph ready for .invoke() / .ainvoke()
    """
    return _create_graph(
        checkpointer=_resolve_checkpointer(config),
        store=_resolve_store(config),
    )


async def run_agent(message: str, thread_id: str = "default") -> dict:
    """Run the agent with a user message.

    Args:
        message: User's message/query
        thread_id: Unique thread ID for conversation

    Returns:
        Final state after processing
    """
    # Build the compiled graph
    app = build_graph()

    # Create config
    config = AgentConfig(thread_id=thread_id).to_dict()

    # Run the graph
    result = await app.ainvoke(
        {"messages": [HumanMessage(content=message)]},
        config=config,
    )

    return result
